deploy:
  provider: rubygems
  api_key:
    secure: ogRuy42rYyOkjt1R8WKDSa9tQzUjOj4QH87QiRpbJ0TcfPkP1OmZkS4SbCsl9W5Tx4VB6ohSUeT0XaEqB2u+eizLkwmm3/wAk4KDw/GUdb+HtwkiJ4xMkX0ARQ6Syz9gy/7pZww58yai/aB5nzDG2+UFK7vJL8rcND//AkcRRQezXoosCbKgjiNHuQHNLn+f6NGQ2W8aDWr1MFHJ3JT2wV5QGV8Su22zJdoaT0IjF6+RsX+7ZJorX9K9adcZ8Igq0RxxybEvM9uFvWL4OM5QVwqjqN6TOeCkqceeYIOX8yk3+ALzvptsy/EFPDkhkQoW1YN4k1paRzyw1z20WQCl0kQjETr5TrTP5cdPkHOF7Qo+NjOe/kEQOAYsl1uDdM/JSL5iDi4IB9UAyupO2FhBPdxgfWRWng3GbD19Nc/j/0O8sLYNo4ysDYQFSBBFwpCxxDVJrotxThrO+LI4VvAQD4yBhjFnGXeLEFMHxHBBY14QWAMrppwxeNKByApFH540FnaqqXMVJsVIRtY1xbF+OXvh67ZYVVJUPNTAZL+uJQwA2YZwt7pdIvr590r5cVSZTAdfu2VF6knyGI+uk4+VIHHImFWKGD3S2rIOkdnVVwUMSvrbJY77qPkXQlrBOYq0pf68FOTzvx6dAPirl1XF9mdac0VSjv8TX4I0Go6GFI0=
  gem: rokka_client_codegen
  on:
    tags: true
    repo: rokka-io/rokka-ruby-codegen
