=begin
#rokka.io

#digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'rokka_client_codegen/api_client'
require 'rokka_client_codegen/api_error'
require 'rokka_client_codegen/version'
require 'rokka_client_codegen/configuration'

# Models
require 'rokka_client_codegen/models/list_source_images_response'
require 'rokka_client_codegen/models/list_stacks_response'
require 'rokka_client_codegen/models/membership'
require 'rokka_client_codegen/models/organization'
require 'rokka_client_codegen/models/organization_definition'
require 'rokka_client_codegen/models/organization_options'
require 'rokka_client_codegen/models/role'
require 'rokka_client_codegen/models/source_image'
require 'rokka_client_codegen/models/stack'
require 'rokka_client_codegen/models/stack_definition'
require 'rokka_client_codegen/models/stack_expression'
require 'rokka_client_codegen/models/stack_expression_overrides'
require 'rokka_client_codegen/models/stack_operation'
require 'rokka_client_codegen/models/stack_operation_description'
require 'rokka_client_codegen/models/stack_options'
require 'rokka_client_codegen/models/user'
require 'rokka_client_codegen/models/user_definition'

# APIs
require 'rokka_client_codegen/api/admin_api'
require 'rokka_client_codegen/api/sourceimages_api'
require 'rokka_client_codegen/api/stacks_api'

module RokkaClientCodegen
  class << self
    # Customize default settings for the SDK using block.
    #   RokkaClientCodegen.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
